apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: go-vwlepvzz
  janus-idp.io/tekton: go-vwlepvzz
  backstage.io/kubernetes-id: go-vwlepvzz
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: go-vwlepvzz
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
